ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
  update_config=1
  country=US

  network={
          ssid="FMU"
          key_mgmt=WPA-EAP
          eap=PEAP
          identity="firstname.lastname"
          password="password"
          phase2="auth-MSCHAPV2"
          priority=1
  }
